# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 2f6030bb4fa1dd777ee480f01bc0c686a4cba0cabd4e6814077e83c85d4fdf0e42b76ccaae292801c75a7df52e32ca33b79816946d5446e346c4cb670dcb3709

test:
  secret_key_base: 2a228fd0ea202ce2dab6850ebe9f2815635fc890552689bd3114279f4f50eab651483a97e01521d15ad271a37914597b2a017c06d62ce26db31703852468adb2

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
